spring:
  profiles:
    active: @spring.profiles.active.value@ # maven profile configuration
  messages:
    basename: i18n/ApplicationResources

  application:
    name: app
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      redis:
        namespace: vdo:session
  datasource:
    druid:
      async-init: true
      initial-size: 10
      min-idle: 10
      max-active: 50
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      test-while-idle: true
      pool-prepared-statements: true
      filters: stat,wall,log4j2
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
      use-global-data-source-stat: true
      aop-patterns: com.daily.english.app.controller.*,com.daily.english.app.service.*,com.daily.english.app.mapper.*
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        reset-enable: false
        url-pattern: /druid/*
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  mail:
    host: mail.chinadailyhk.com
    username: ed@chinadailyhk.com
    password: English20160118
    default-encoding: utf-8



server:
  servlet:
    context-path: /app
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 16
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 100
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true

logging:
  level:
    root: debug

io:
  lettuce:
    core:
      epoll: true
      kqueue: true

mybatis:
  mapper-locations: "classpath*:mapper/*.xml"
  type-handlers-package: com.daily.english.app.mybatis
  configuration:
    cache-enabled: true
    default-statement-timeout: 3000
    map-underscore-to-camel-case: true
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl

# pagehelper分页插件配置
pagehelper:
  # 输入的页数不在合法范围仍然响应到正确的结果页面
  reasonable: true
  support-methods-arguments: true
  # 当 pageSize=0 或者 RowBounds.limit = 0 就会查询出全部的结果
  page-size-zero: true

# Session 过期时间（单位：秒）
session.timeout: 1800

datasource.mysql.parameters: zeroDateTimeBehavior=CONVERT_TO_NULL&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true